version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
    ports:
      - "${PORT}:${PORT}" 
    env_file:
      - .env 
    depends_on:
      - db 
    volumes:
      - .:/usr/src/app
    command: npm run start:prod
    networks:
      - nest-network

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"  # Пробрасываем порт для PostgreSQL
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nest-network
      
  migration:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: npm run migrate
    depends_on:
      - db
    networks:
      - nest-network

volumes:
  pgdata:
    driver: local

networks:
  nest-network:
    driver: bridge