version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis  # Добавляем переменную окружения для Redis
    ports:
      - "${PORT}:${PORT}" 
    env_file:
      - .env 
    depends_on:
      - db 
      - redis 
    volumes:
      - .:/usr/src/app
    command: npm run start:prod
    networks:
      - nest-network

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nest-network

  migration:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: npm run migrate
    depends_on:
      - db
    networks:
      - nest-network

  redis:  
    image: redis:latest
    ports:
      - "6379:6379"  
    networks:
      - nest-network

volumes:
  pgdata:
    driver: local

networks:
  nest-network:
    driver: bridge